config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :citations
  get "random", to: "citations#random", as: :random_citation
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/citation.rb
class Citation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController
  def index
    @citations = Citation.all
  end

  def show
    @citation = Citation.find(params[:id])
  end

  def new
    @citation = Citation.new
  end

  def create
    @citation = Citation.new(citation_params)
    if @citation.save
      redirect_to @citation, notice: 'La citation a été crée avec succès.'
    else
      render :new
    end
  end

  def random
    citation_random = Citation.order("RANDOM()").take
    redirect_to citation_path(citation_random)
  end

  def edit
    @citation = Citation.find(params[:id])
  end

  def update
    @citation = Citation.find(params[:id])
    if @citation.update(citation_params)
      redirect_to @citation, notice: 'La citation a été mise à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    @citation = Citation.find(params[:id])
    @citation.destroy
    redirect_to citations_path, notice: 'La citation a été supprimée avec succès.'
  end

  private

  def citation_params
    params.require(:citation).permit(:auteur, :contenu, :categorie)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/citations/_form.html.erb
<div class="container">
  <div class="row d-flex justify-content-center align-items-center">
    <div class="col-6">
      <div class="form">
        <div class="form-content">
          <%= simple_form_for(@citation) do |f| %>
          <%= f.input :contenu %>
          <%= f.input :auteur %>
          <%= f.input :categorie %>
          <%= f.submit "Créer", class:"btn-creer me-3"%>
          <%= link_to "Annuler", citations_path %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/citations/edit.html.erb
<%= render "form", citation: @citation %>

app/views/citations/index.html.erb
<div class="container d-flex flex-column">
  <div class="accueil">
     <%= link_to root_path do %>
    <i class="fa-solid fa-house"></i>
    <% end %>
  </div>
  <div class="justify-content-center">
    <div class="citations">

        <% @citations.each do |citation| %>
        <%= link_to citation_path(citation) do %>
          <% if citation.categorie == "philosophie" %>
              <div class="citations-card-philosophie">
            <% else %>
              <div class="citations-card">
            <% end %>
            <p class="text-truncate"><%= citation.contenu %></p>
            <%= citation.auteur %>
            <div class="d-flex align-items-end justify-content-end">
              <p class = "categorie"><em><%= citation.categorie %></em></p>
            </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/citations/new.html.erb
<%= render 'form' %>

app/views/citations/show.html.erb
<div class="container">
    <div class="citation-show">
      <p class="citation-contenu-show">"<%= @citation.contenu %>"</p>
      <p class="mt-5"><%= @citation.auteur %></p>
    </div>
    <div class="links-show d-flex justify-content-end">
      <%= link_to citations_path do%>
      <i class="fa-solid fa-arrow-left me-4"></i>
      <% end %>
      <%= link_to edit_citation_path(@citation) do %>
      <i class="fa-solid fa-pen-to-square me-4"></i>
      <% end %>
      <%= link_to citation_path(@citation), data: { turbo_method: :delete, turbo_confirm: "Are you sure" } do  %>
      <i class="fa-solid fa-trash"></i>
      <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Citations</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Amita:wght@400;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="home d-flex flex-column justify-content-center align-items-center">
    <div class="mes-citations d-flex flex-column justify-content-center align-items-center">
      <p >Mes citations</p>
       <div class="links d-flex justify-content-center">
      <p><%= link_to "Voir toutes les citations", citations_path, class:"btn-home"%></p>
      <p><%= link_to "Ajouter une citation", new_citation_path , class:"btn-home" %></p>
      <p><%= link_to "Une citation au hasard", random_citation_path, class:"btn-home" %></p>
    </div>
    </div>
  </div>
</div>